apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-dashboard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dashboard
  template:
    metadata:
      labels:
        app: dashboard
    spec:
      containers:
        - name: dashboard
          image: tominsahu/k8s-dashboard:latest
          ports:
            - containerPort: 5000
